@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
!include DEVICONS/nodejs.puml
!include DEVICONS/react.puml
!include DEVICONS/mysql.puml

LAYOUT_WITH_LEGEND()

AddRelTag("Async", $lineStyle= DashedLine())

title "Sistema XPTO"

Person(user, "Usuário", "Pessoas que vão acessar o site", $sprite="users")
    
System_Ext(payment_gateway, "Payment Gateway", "Payment Processor")

System_Boundary(Dockerfile, "Sistema XPTO"){
    Container(spa, "SPA", "SPA", "Interface que os usuários interagem", $sprite="spa")
    Container(XPTO_core, "XPTO Core", "TS", "Logica de negócios", $sprite="typescript")
    Container(reactAPP, "React APP", "react", "Interface do usuário construida pelo REACT ", $sprite="react")
    Container(reactNativeAPP, "React Native APP", "react", "Interface do usuário construida pelo REACT Native ", $sprite="reactnative")
    Container(balance_service, "Balance Service", "TS", "Serviço de saldo", $sprite="typescript")
    Container(statements_service, "Statements Service", "TS", "Serviço de extrato", $sprite="typescript")
    Container(payment_acl, "Payment Service", "TS", "Anticorruption Layer for Payment", $sprite="typescript")

    ContainerDb(XPTO_core_db, "XPTO Core DB", "Banco de Dados", "Armazenamento de dados", $sprite="mysql")  
    Rel(XPTO_core, XPTO_core_db, "Usa", "MySQL Driver")

    ContainerDb(balance_service_db, "Balance Service DB", "Banco de Dados", "Armazenamento de dados", $sprite="mysql")  
    Rel(balance_service, balance_service_db, "Usa", "MySQL Driver")

    ContainerDb(statements_service_db, "Statements Service DB", "Banco de Dados", "Armazenamento de dados", $sprite="mysql")  
    Rel(statements_service, statements_service_db, "Usa", "MySQL Driver")

    ContainerDb(payment_acl_db, "Payment Service DB", "Banco de Dados", "Armazenamento de dados", $sprite="mysql")  
    Rel(payment_acl, payment_acl_db, "Usa", "MySQL Driver")
    
    ContainerDb(payment_acl_db, "Payment Service DB", "Banco de Dados", "Armazenamento de dados", $sprite="mysql")  
    Rel(payment_acl, payment_gateway, "Usa", "MySQL Driver")

    Rel(user, spa, "Usa", "https")
    Rel_R(spa, reactAPP, "Compõe", "https")
    Rel_R(spa, reactNativeAPP, "Compõe", "https")
    Rel(spa, XPTO_core, "Usa", "https")
    Rel(spa, balance_service, "Usa", "https")
    Rel(spa, statements_service, "Usa", "https")

    Rel(XPTO_core, balance_service, "Usa", "Topic", $tags="Async")
    Rel(XPTO_core, statements_service, "Usa", "Topic", $tags="Async")
    Rel(XPTO_core, payment_acl, "Usa", "Topic")
    ' Rel(XPTO_core, balance_service, "Usa", "Topic")
}
@enduml