@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
!include DEVICONS/nodejs.puml
!include DEVICONS/react.puml
!include DEVICONS/mysql.puml

LAYOUT_WITH_LEGEND()

Person(user, "Usuário", "Pessoas que vão acessar o site", $sprite="users")
    
    System(system, "Sistema", "Sistema que recebe a solicitação do usuário")

System_Boundary(Dockerfile, "Container A"){
    Container(spa, "SPA", "SPA", "Interface que os usuários interagem", $sprite="spa")
    Container(nodejs, "Back-End", "nodejs", "Logica de negócios", $sprite="nodejs")
    Container(reactAPP, "React APP", "react", "Interface do usuário construida pelo REACT ", $sprite="react")
    Container(express, "Express", "nodejs", "Framework web", $sprite="express")

    Rel(user, system, "Usa", "https")
    Rel(system, spa, "Implementa", "https")
    Rel_R(spa, reactAPP, "Compõe", "https")
    Rel(spa, nodejs, "Acessando o NodeJS", "https")
    Rel(spa, express, "Acessando o Express", "https")
    Rel(nodejs, express, "Acessando o Express", "https")
}
@enduml