@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
!include DEVICONS/nodejs.puml
!include DEVICONS/react.puml 
!include DEVICONS/mysql.puml

LAYOUT_WITH_LEGEND()

Person(user, "Usuário", "Pessoas que vão acessar o site", $sprite="users")
    
System(system, "Sistema", "Sistema que recebe a solicitação do usuário")

System_Boundary(Dockerfile, "Container A"){
    Container(spa, "SPA", "express", "The main interface that the customer interacts with")
    Container(api, "Back-End", "nodejs", "Handles all business logic", $sprite="nodejs")
    Container(reactApp, "React App", "react", "User interface built with React", $sprite="react") ! Adiciona o contêiner React
}

Rel(user, system, "Solicita a página", "https")
Rel(system, spa, "Acessando o container docker (express + nodejs)", "https")
Rel_R(spa, api, "Acessando o NodeJS", "https")
Rel_R(spa, reactApp, "Renderiza a interface React", "https") ! Conecta o SPA (Express) ao React

@enduml
