@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/angular.puml
!include DEVICONS/java.puml
!include DEVICONS/msql_server.puml
!include FONTAWESOME/users.puml
!include DEVICONS/nodejs.puml
!include DEVICONS/react.puml
!include DEVICONS/mysql.puml

LAYOUT_WITH_LEGEND()

Person(user, "Customer", "People that need products", $sprite="users")
Container(spa, "SPA", "express", "The main interface that the customer interacts with")
Container(api, "API", "nodejs", "Handles all business logic", $sprite="nodejs")
---ContainerDb(db, "Database", "My SQL", "Holds product, order and invoice information", $sprite="mysql")

Rel(user, spa, "Uses", "https")
Rel(spa, api, "Uses", "https")
--Rel_R(api, db, "Reads/Writes")
@enduml