@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
!include DEVICONS/nodejs.puml
!include DEVICONS/mysql.puml

LAYOUT_WITH_LEGEND()

Person(user, "Customer", "People that need see the site", $sprite="users")

System_Boundary(Dockerfile, "Dockerfile", "teste"){
    Container(spa, "SPA", "express", "The main interface that the customer interacts with")
    Container(api, "Back-End", "nodejs", "Handles all business logic", $sprite="nodejs")
}


Rel(user, spa, "Uses", "https")
Rel_R(spa, api, "Uses", "https")
@enduml